# Generated by Django 2.0.5 on 2018-12-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddModification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_title', models.CharField(choices=[('ENLARGE', 'ENLARGE'), ('SHORTEN', 'SHORTEN')], max_length=250)),
                ('modification_price', models.CharField(max_length=250, null=True)),
                ('modification_comment', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
